### ISSUE TITLE
Missing support for .NET Standard

### ISSUE THREAD

**Issue by luigiberrettini** [VaughnVernon/mockroservices-dotnet#4]
I [ported](https://github.com/luigiberrettini/mockroservices-dotnet) your code to .NET Standard (the test suite to .NET Core), but do not know if you prefer to have a separate repository or evaluate a PR on this one

To make the repo useful it would be nice to create a NuGet package

**Comment by VaughnVernon** [comment]
Thanks, Luigi! Not sure, but I think it should be a separate repository. The question is, will all .NET developers have the environment to run Core/Standard, or will some still be on Framework?

If you agree it should be a separate repository, what would you name it?
- mockroservices-netcore
- mockroservices-netcorestd
- mockroservices-netstd
- ???

**Comment by luigiberrettini** [comment]
The repo is yours, therefore any decision is fine to me.

Here follow some considerations:
 - Microsoft is pushing for .NET Core
 - requirements for .NET Core are lower (install the SDK and you can just use Notepad and the command line)
 - the Mockroservices library can target both .NET Standard and .NET 4.x so that it can be consumed by applications written in both .NET Core and .NET classic framework

In case you decide for a separate repo, I think the name could be mockroservices-netstd (ignoring that tests are in .NET Core)

It would be really great to create a NuGet package like VaughnVernon.Mockroservices so that people can just add it to their dependencies and program against the lib (it can be done with an AppVeyor build script and I can help on this too)

**Comment by tjaskula** [comment]
Also I think that there is no point in keeping both. The .net standard version is enough to make it work for both .net framework and .net core implementing the standard. @luigiberrettini did you have a chance to move forward with it or it is sleeping in your fork ?

**Comment by VaughnVernon** [comment]
@tjaskula I have an update that I will push today. I do now distribute the newer one with the workshop exercises so no worries either way. Also it's all .NET Core 2.1 now.
